name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify lockfile
        run: |
          [ -f pnpm-lock.yaml ] || (echo "pnpm-lock.yaml not found!" && exit 1)

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Остальные ваши шаги...
      - name: Setup SSH key
        run: |
          mkdir -p "$HOME/.ssh"
          echo "${{ secrets.key }}" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"

      - name: Build project
        run: pnpm run build

      - name: Test SSH connectivity
        run: |
          ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no -o BatchMode=yes yakoonina@gmail.com 'echo "SSH OK"'

      - name: Deploy with rsync
        run: |
          cd dist && rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no -o BatchMode=yes" --archive --compress --delete . yakoonina@gmail.com:/var/www/ui-kit-tailwind/html/
